### ISSUE TITLE
UI does not know when to swap players based on spawn. 

### ISSUE THREAD

**Issue by msibs** [kuschAoe/AoE4_ObserverUI#1]
UI does not know when to swap players based on spawn.

**Comment by msibs** [comment]
You may be able to use this to correct it.
```
function TestPlayerPositions() 
	local p1 = Player_GetStartingPoisition(0)
	local p2 = Player_GetStartingPoisition(1)
	local p1t = p1[1] + p1[2]
	local p2t = p2[1] + p2[2]
	
	if p2t < p1t then
		SwapPlayers1v1()
	end	
end 	
```

**Comment by kuschAoe** [comment]
I'll update the mod this week including your suggested change and a button to swap players manually for when you want them always on the same side during a series for instance.
